//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:36:06 PM EEST 
//


package be.fgov.ejustice.ejustbox.consultation.protocol.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import be.fgov.ejustice.ejustbox.core.v1.AcknowledgmentType;
import be.fgov.ejustice.ejustbox.core.v1.ErrorType;


/**
 * Contains all elements relative to the content of the message
 * 
 * <p>Java class for ConsultationContentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsultationContentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Document" type="{urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1}ConsultationDocumentType"/&gt;
 *         &lt;element name="EncryptableINSSPerson" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Annex" type="{urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1}ConsultationAnnexType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Acknowledgment" type="{urn:be:fgov:ejustice:ejustbox:core:v1}AcknowledgmentType" minOccurs="0"/&gt;
 *         &lt;element name="Error" type="{urn:be:fgov:ejustice:ejustbox:core:v1}ErrorType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsultationContentType", propOrder = {
    "document",
    "encryptableINSSPerson",
    "annex",
    "acknowledgment",
    "error"
})
public class ConsultationContentType {

    @XmlElement(name = "Document", required = true)
    protected ConsultationDocumentType document;
    @XmlElement(name = "EncryptableINSSPerson")
    protected List<byte[]> encryptableINSSPerson;
    @XmlElement(name = "Annex")
    protected List<ConsultationAnnexType> annex;
    @XmlElement(name = "Acknowledgment")
    protected AcknowledgmentType acknowledgment;
    @XmlElement(name = "Error")
    protected ErrorType error;

    /**
     * Gets the value of the document property.
     * 
     * @return
     *     possible object is
     *     {@link ConsultationDocumentType }
     *     
     */
    public ConsultationDocumentType getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsultationDocumentType }
     *     
     */
    public void setDocument(ConsultationDocumentType value) {
        this.document = value;
    }

    /**
     * Gets the value of the encryptableINSSPerson property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the encryptableINSSPerson property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEncryptableINSSPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * byte[]
     * 
     */
    public List<byte[]> getEncryptableINSSPerson() {
        if (encryptableINSSPerson == null) {
            encryptableINSSPerson = new ArrayList<byte[]>();
        }
        return this.encryptableINSSPerson;
    }

    /**
     * Gets the value of the annex property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annex property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnex().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConsultationAnnexType }
     * 
     * 
     */
    public List<ConsultationAnnexType> getAnnex() {
        if (annex == null) {
            annex = new ArrayList<ConsultationAnnexType>();
        }
        return this.annex;
    }

    /**
     * Gets the value of the acknowledgment property.
     * 
     * @return
     *     possible object is
     *     {@link AcknowledgmentType }
     *     
     */
    public AcknowledgmentType getAcknowledgment() {
        return acknowledgment;
    }

    /**
     * Sets the value of the acknowledgment property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcknowledgmentType }
     *     
     */
    public void setAcknowledgment(AcknowledgmentType value) {
        this.acknowledgment = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }

}
