//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:36:06 PM EEST 
//


package be.fgov.ejustice.ejustbox.consultation.protocol.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import be.fgov.ejustice.commons.protocol.v1.StatusResponseType;


/**
 * <p>Java class for GetBoxInfoResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetBoxInfoResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:be:fgov:ejustice:commons:protocol:v1}StatusResponseType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="NbrMessagesInStandBy" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="NbrUnreadMessages" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CurrentSize" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="MaxSize" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetBoxInfoResponseType", propOrder = {
    "nbrMessagesInStandBy",
    "nbrUnreadMessages",
    "currentSize",
    "maxSize"
})
public class GetBoxInfoResponseType
    extends StatusResponseType
{

    @XmlElement(name = "NbrMessagesInStandBy")
    protected Integer nbrMessagesInStandBy;
    @XmlElement(name = "NbrUnreadMessages")
    protected Integer nbrUnreadMessages;
    @XmlElement(name = "CurrentSize")
    protected Long currentSize;
    @XmlElement(name = "MaxSize")
    protected Long maxSize;

    /**
     * Gets the value of the nbrMessagesInStandBy property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNbrMessagesInStandBy() {
        return nbrMessagesInStandBy;
    }

    /**
     * Sets the value of the nbrMessagesInStandBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNbrMessagesInStandBy(Integer value) {
        this.nbrMessagesInStandBy = value;
    }

    /**
     * Gets the value of the nbrUnreadMessages property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNbrUnreadMessages() {
        return nbrUnreadMessages;
    }

    /**
     * Sets the value of the nbrUnreadMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNbrUnreadMessages(Integer value) {
        this.nbrUnreadMessages = value;
    }

    /**
     * Gets the value of the currentSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCurrentSize() {
        return currentSize;
    }

    /**
     * Sets the value of the currentSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCurrentSize(Long value) {
        this.currentSize = value;
    }

    /**
     * Gets the value of the maxSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxSize() {
        return maxSize;
    }

    /**
     * Sets the value of the maxSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxSize(Long value) {
        this.maxSize = value;
    }

}
