//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:36:06 PM EEST 
//


package be.fgov.ejustice.ejustbox.consultation.protocol.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import be.fgov.ejustice.commons.protocol.v1.StatusResponseType;
import be.fgov.ejustice.ejustbox.core.v1.ActorType;
import be.fgov.ejustice.ejustbox.core.v1.MessageInfoType;


/**
 * <p>Java class for GetFullMessageResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetFullMessageResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:be:fgov:ejustice:commons:protocol:v1}StatusResponseType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="Sender" type="{urn:be:fgov:ejustice:ejustbox:core:v1}ActorType"/&gt;
 *         &lt;element name="Message" type="{urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1}ConsultationMessageType"/&gt;
 *         &lt;element name="MessageInfo" type="{urn:be:fgov:ejustice:ejustbox:core:v1}MessageInfoType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetFullMessageResponseType", propOrder = {
    "sender",
    "message",
    "messageInfo"
})
public class GetFullMessageResponseType
    extends StatusResponseType
{

    @XmlElement(name = "Sender")
    protected ActorType sender;
    @XmlElement(name = "Message")
    protected ConsultationMessageType message;
    @XmlElement(name = "MessageInfo")
    protected MessageInfoType messageInfo;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link ActorType }
     *     
     */
    public ActorType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActorType }
     *     
     */
    public void setSender(ActorType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link ConsultationMessageType }
     *     
     */
    public ConsultationMessageType getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsultationMessageType }
     *     
     */
    public void setMessage(ConsultationMessageType value) {
        this.message = value;
    }

    /**
     * Gets the value of the messageInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MessageInfoType }
     *     
     */
    public MessageInfoType getMessageInfo() {
        return messageInfo;
    }

    /**
     * Sets the value of the messageInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageInfoType }
     *     
     */
    public void setMessageInfo(MessageInfoType value) {
        this.messageInfo = value;
    }

	@Override
	public String toString() {
		return "GetFullMessageResponseType [sender=" + sender + ", message=" + message + ", messageInfo=" + messageInfo
				+ ", status=" + status + ", id=" + id + ", inResponseTo=" + inResponseTo + ", issueInstant="
				+ issueInstant + "]";
	}
    
    
    

}
