//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:36:06 PM EEST 
//


package be.fgov.ejustice.ejustbox.consultation.protocol.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import be.fgov.ejustice.commons.protocol.v1.StatusResponseType;
import be.fgov.ejustice.ejustbox.core.v1.EJustboxSubstituteType;


/**
 * <p>Java class for GetOoOListResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetOoOListResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:be:fgov:ejustice:commons:protocol:v1}StatusResponseType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="OoO" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="OoOId" type="{urn:be:fgov:ejustice:ejustbox:core:v1}OoOIdType"/&gt;
 *                   &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="Substitute" type="{urn:be:fgov:ejustice:ejustbox:core:v1}EJustboxSubstituteType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetOoOListResponseType", propOrder = {
    "ooO"
})
public class GetOoOListResponseType
    extends StatusResponseType
{

    @XmlElement(name = "OoO")
    protected List<GetOoOListResponseType.OoO> ooO;

    /**
     * Gets the value of the ooO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ooO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOoO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetOoOListResponseType.OoO }
     * 
     * 
     */
    public List<GetOoOListResponseType.OoO> getOoO() {
        if (ooO == null) {
            ooO = new ArrayList<GetOoOListResponseType.OoO>();
        }
        return this.ooO;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="OoOId" type="{urn:be:fgov:ejustice:ejustbox:core:v1}OoOIdType"/&gt;
     *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="Substitute" type="{urn:be:fgov:ejustice:ejustbox:core:v1}EJustboxSubstituteType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ooOId",
        "startDate",
        "endDate",
        "substitute"
    })
    public static class OoO {

        @XmlElement(name = "OoOId", required = true)
        protected String ooOId;
        @XmlElement(name = "StartDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar startDate;
        @XmlElement(name = "EndDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar endDate;
        @XmlElement(name = "Substitute")
        protected List<EJustboxSubstituteType> substitute;

        /**
         * Gets the value of the ooOId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOoOId() {
            return ooOId;
        }

        /**
         * Sets the value of the ooOId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOoOId(String value) {
            this.ooOId = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartDate(XMLGregorianCalendar value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the substitute property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the substitute property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubstitute().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EJustboxSubstituteType }
         * 
         * 
         */
        public List<EJustboxSubstituteType> getSubstitute() {
            if (substitute == null) {
                substitute = new ArrayList<EJustboxSubstituteType>();
            }
            return this.substitute;
        }

    }

}
