//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:36:06 PM EEST 
//


package be.fgov.ejustice.ejustbox.consultation.protocol.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import be.fgov.ejustice.commons.protocol.v1.StatusResponseType;


/**
 * <p>Java class for InsertOoOResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsertOoOResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:be:fgov:ejustice:commons:protocol:v1}StatusResponseType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="OoOId" type="{urn:be:fgov:ejustice:ejustbox:core:v1}OoOIdType" minOccurs="0"/&gt;
 *         &lt;element name="Substitute" type="{urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1}SubstituteType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsertOoOResponseType", propOrder = {
    "ooOId",
    "substitute"
})
public class InsertOoOResponseType
    extends StatusResponseType
{

    @XmlElement(name = "OoOId")
    protected String ooOId;
    @XmlElement(name = "Substitute")
    protected List<SubstituteType> substitute;

    /**
     * Gets the value of the ooOId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOoOId() {
        return ooOId;
    }

    /**
     * Sets the value of the ooOId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOoOId(String value) {
        this.ooOId = value;
    }

    /**
     * Gets the value of the substitute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substitute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubstitute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstituteType }
     * 
     * 
     */
    public List<SubstituteType> getSubstitute() {
        if (substitute == null) {
            substitute = new ArrayList<SubstituteType>();
        }
        return this.substitute;
    }

}
