//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:38:38 PM EEST 
//


package be.fgov.ejustice.ejustbox.publication.protocol.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import be.fgov.ejustice.ejustbox.core.v1.EJustboxIdentifierType;


/**
 * <p>Java class for DestinationContextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DestinationContextType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:be:fgov:ejustice:ejustbox:core:v1}EJustboxIdentifierType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="OoOProcessed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DestinationContextType", propOrder = {
    "ooOProcessed"
})
public class DestinationContextType
    extends EJustboxIdentifierType
{

    @XmlElement(name = "OoOProcessed")
    protected Boolean ooOProcessed;

    /**
     * Gets the value of the ooOProcessed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOoOProcessed() {
        return ooOProcessed;
    }

    /**
     * Sets the value of the ooOProcessed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOoOProcessed(Boolean value) {
        this.ooOProcessed = value;
    }

}
