//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:38:38 PM EEST 
//


package be.fgov.ejustice.ejustbox.publication.protocol.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.fgov.ejustice.ejustbox.publication.protocol.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendMessageRequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:publication:protocol:v1", "SendMessageRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.fgov.ejustice.ejustbox.publication.protocol.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link PublicationMessageType }
     * 
     */
    public PublicationMessageType createPublicationMessageType() {
        return new PublicationMessageType();
    }

    /**
     * Create an instance of {@link SendMessageResponse.Recipient }
     * 
     */
    public SendMessageResponse.Recipient createSendMessageResponseRecipient() {
        return new SendMessageResponse.Recipient();
    }

    /**
     * Create an instance of {@link DestinationContextType }
     * 
     */
    public DestinationContextType createDestinationContextType() {
        return new DestinationContextType();
    }

    /**
     * Create an instance of {@link PublicationContentType }
     * 
     */
    public PublicationContentType createPublicationContentType() {
        return new PublicationContentType();
    }

    /**
     * Create an instance of {@link ContentSpecificationType }
     * 
     */
    public ContentSpecificationType createContentSpecificationType() {
        return new ContentSpecificationType();
    }

    /**
     * Create an instance of {@link ContentContextType }
     * 
     */
    public ContentContextType createContentContextType() {
        return new ContentContextType();
    }

    /**
     * Create an instance of {@link PublicationAnnexType }
     * 
     */
    public PublicationAnnexType createPublicationAnnexType() {
        return new PublicationAnnexType();
    }

    /**
     * Create an instance of {@link PublicationDocumentType }
     * 
     */
    public PublicationDocumentType createPublicationDocumentType() {
        return new PublicationDocumentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicationMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:publication:protocol:v1", name = "SendMessageRequest")
    public JAXBElement<PublicationMessageType> createSendMessageRequest(PublicationMessageType value) {
        return new JAXBElement<PublicationMessageType>(_SendMessageRequest_QNAME, PublicationMessageType.class, null, value);
    }

}
