//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:38:38 PM EEST 
//


package be.fgov.ejustice.ejustbox.publication.protocol.v1;

import java.util.Arrays;

import javax.activation.DataHandler;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttachmentRef;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies content of an Annex
 * 
 * <p>Java class for PublicationAnnexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicationAnnexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EncryptableTitle" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="EncryptableContent" type="{http://ws-i.org/profiles/basic/1.1/xsd}swaRef"/&gt;
 *         &lt;element name="DownloadFileName"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MimeType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Digest" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicationAnnexType", propOrder = {
    "encryptableTitle",
    "encryptableContent",
    "downloadFileName",
    "mimeType",
    "digest"
})
public class PublicationAnnexType {

    @XmlElement(name = "EncryptableTitle", required = true)
    protected byte[] encryptableTitle;
    @XmlElement(name = "EncryptableContent", required = true, type = String.class)
    @XmlAttachmentRef
    @XmlSchemaType(name = "anyURI")
    protected DataHandler encryptableContent;
    @XmlElement(name = "DownloadFileName", required = true)
    protected String downloadFileName;
    @XmlElement(name = "MimeType", required = true)
    protected String mimeType;
    @XmlElement(name = "Digest", required = true)
    protected String digest;

    /**
     * Gets the value of the encryptableTitle property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getEncryptableTitle() {
        return encryptableTitle;
    }

    /**
     * Sets the value of the encryptableTitle property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setEncryptableTitle(byte[] value) {
        this.encryptableTitle = value;
    }

    /**
     * Gets the value of the encryptableContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DataHandler getEncryptableContent() {
        return encryptableContent;
    }

    /**
     * Sets the value of the encryptableContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptableContent(DataHandler value) {
        this.encryptableContent = value;
    }

    /**
     * Gets the value of the downloadFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDownloadFileName() {
        return downloadFileName;
    }

    /**
     * Sets the value of the downloadFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDownloadFileName(String value) {
        this.downloadFileName = value;
    }

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMimeType() {
        return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMimeType(String value) {
        this.mimeType = value;
    }

    /**
     * Gets the value of the digest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigest() {
        return digest;
    }

    /**
     * Sets the value of the digest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigest(String value) {
        this.digest = value;
    }

	@Override
	public String toString() {
		return "PublicationAnnexType [encryptableTitle=" + Arrays.toString(encryptableTitle) + ", encryptableContent="
				+ encryptableContent + ", downloadFileName=" + downloadFileName + ", mimeType=" + mimeType + ", digest="
				+ digest + "]";
	}
    
    

}
