//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:38:38 PM EEST 
//


package be.fgov.ejustice.ejustbox.publication.protocol.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import be.fgov.ejustice.commons.protocol.v1.StatusResponseType;
import be.fgov.ejustice.ejustbox.core.v1.EJustboxIdentifierType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:be:fgov:ejustice:commons:protocol:v1}StatusResponseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SentPublicationId" type="{urn:be:fgov:ejustice:ejustbox:core:v1}PublicationIdType"/&gt;
 *         &lt;element name="MessageId" type="{urn:be:fgov:ejustice:ejustbox:core:v1}MessageIdType" minOccurs="0"/&gt;
 *         &lt;element name="Recipient" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{urn:be:fgov:ejustice:ejustbox:core:v1}EJustboxIdentifierType"&gt;
 *                 &lt;sequence minOccurs="0"&gt;
 *                   &lt;element name="AbsentFrom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="AbsentTo" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="Substitute" type="{urn:be:fgov:ejustice:ejustbox:core:v1}EJustboxIdentifierType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sentPublicationId",
    "messageId",
    "recipient"
})
@XmlRootElement(name = "SendMessageResponse")
public class SendMessageResponse
    extends StatusResponseType
{

    @XmlElement(name = "SentPublicationId", required = true)
    protected String sentPublicationId;
    @XmlElement(name = "MessageId")
    protected String messageId;
    @XmlElement(name = "Recipient")
    protected List<SendMessageResponse.Recipient> recipient;

    /**
     * Gets the value of the sentPublicationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentPublicationId() {
        return sentPublicationId;
    }

    /**
     * Sets the value of the sentPublicationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentPublicationId(String value) {
        this.sentPublicationId = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recipient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecipient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SendMessageResponse.Recipient }
     * 
     * 
     */
    public List<SendMessageResponse.Recipient> getRecipient() {
        if (recipient == null) {
            recipient = new ArrayList<SendMessageResponse.Recipient>();
        }
        return this.recipient;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{urn:be:fgov:ejustice:ejustbox:core:v1}EJustboxIdentifierType"&gt;
     *       &lt;sequence minOccurs="0"&gt;
     *         &lt;element name="AbsentFrom" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="AbsentTo" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="Substitute" type="{urn:be:fgov:ejustice:ejustbox:core:v1}EJustboxIdentifierType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "absentFrom",
        "absentTo",
        "substitute"
    })
    public static class Recipient
        extends EJustboxIdentifierType
    {

        @XmlElement(name = "AbsentFrom")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar absentFrom;
        @XmlElement(name = "AbsentTo")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar absentTo;
        @XmlElement(name = "Substitute")
        protected List<EJustboxIdentifierType> substitute;

        /**
         * Gets the value of the absentFrom property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getAbsentFrom() {
            return absentFrom;
        }

        /**
         * Sets the value of the absentFrom property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setAbsentFrom(XMLGregorianCalendar value) {
            this.absentFrom = value;
        }

        /**
         * Gets the value of the absentTo property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getAbsentTo() {
            return absentTo;
        }

        /**
         * Sets the value of the absentTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setAbsentTo(XMLGregorianCalendar value) {
            this.absentTo = value;
        }

        /**
         * Gets the value of the substitute property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the substitute property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubstitute().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EJustboxIdentifierType }
         * 
         * 
         */
        public List<EJustboxIdentifierType> getSubstitute() {
            if (substitute == null) {
                substitute = new ArrayList<EJustboxIdentifierType>();
            }
            return this.substitute;
        }

    }


	@Override
	public String toString() {
		return "SendMessageResponse [sentPublicationId=" + sentPublicationId + ", messageId=" + messageId
				+ ", recipient=" + recipient + ", status=" + status + ", id=" + id + "]";
	}
    
    

}
