//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:38:38 PM EEST 
//


package be.fgov.ejustice.ejustbox.core.v1;

import java.util.Arrays;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Info about the message content, without transmitting everything
 * 
 * <p>Java class for ContentInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EncryptableINSSPerson" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="Title"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="400"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MimeType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="HasAnnex" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentInfoType", propOrder = {
    "encryptableINSSPerson",
    "title",
    "mimeType",
    "hasAnnex"
})
public class ContentInfoType {

    @XmlElement(name = "EncryptableINSSPerson")
    protected byte[] encryptableINSSPerson;
    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "MimeType", required = true)
    protected String mimeType;
    @XmlElement(name = "HasAnnex")
    protected boolean hasAnnex;

    /**
     * Gets the value of the encryptableINSSPerson property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getEncryptableINSSPerson() {
        return encryptableINSSPerson;
    }

    /**
     * Sets the value of the encryptableINSSPerson property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setEncryptableINSSPerson(byte[] value) {
        this.encryptableINSSPerson = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMimeType() {
        return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMimeType(String value) {
        this.mimeType = value;
    }

    /**
     * Gets the value of the hasAnnex property.
     * 
     */
    public boolean isHasAnnex() {
        return hasAnnex;
    }

    /**
     * Sets the value of the hasAnnex property.
     * 
     */
    public void setHasAnnex(boolean value) {
        this.hasAnnex = value;
    }

	@Override
	public String toString() {
		return "ContentInfoType [encryptableINSSPerson=" + Arrays.toString(encryptableINSSPerson) + ", title=" + title
				+ ", mimeType=" + mimeType + ", hasAnnex=" + hasAnnex + "]";
	}

    
    
}
