//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:38:38 PM EEST 
//


package be.fgov.ejustice.ejustbox.core.v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.fgov.ejustice.ejustbox.core.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.fgov.ejustice.ejustbox.core.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EJustboxIdentifierType }
     * 
     */
    public EJustboxIdentifierType createEJustboxIdentifierType() {
        return new EJustboxIdentifierType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link AcknowledgmentType }
     * 
     */
    public AcknowledgmentType createAcknowledgmentType() {
        return new AcknowledgmentType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link EJustboxSubstituteType }
     * 
     */
    public EJustboxSubstituteType createEJustboxSubstituteType() {
        return new EJustboxSubstituteType();
    }

    /**
     * Create an instance of {@link MetaType }
     * 
     */
    public MetaType createMetaType() {
        return new MetaType();
    }

    /**
     * Create an instance of {@link CustomMetaType }
     * 
     */
    public CustomMetaType createCustomMetaType() {
        return new CustomMetaType();
    }

    /**
     * Create an instance of {@link ContentInfoType }
     * 
     */
    public ContentInfoType createContentInfoType() {
        return new ContentInfoType();
    }

    /**
     * Create an instance of {@link ContentSpecificationType }
     * 
     */
    public ContentSpecificationType createContentSpecificationType() {
        return new ContentSpecificationType();
    }

    /**
     * Create an instance of {@link MessageInfoType }
     * 
     */
    public MessageInfoType createMessageInfoType() {
        return new MessageInfoType();
    }

    /**
     * Create an instance of {@link ActorType }
     * 
     */
    public ActorType createActorType() {
        return new ActorType();
    }

    /**
     * Create an instance of {@link EJustboxIdentifierType.User }
     * 
     */
    public EJustboxIdentifierType.User createEJustboxIdentifierTypeUser() {
        return new EJustboxIdentifierType.User();
    }

}
