//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.23 at 02:53:20 PM EEST 
//


package org.crama.ejustbox.model.consultation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Get a message with it's content
 * 
 * <p>Java class for ConsultationMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsultationMessageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PublicationId" type="{urn:be:fgov:ejustice:ejustbox:core:v1}PublicationIdType" minOccurs="0"/&gt;
 *         &lt;element name="DestinationContext" type="{urn:be:fgov:ejustice:ejustbox:core:v1}EJustboxIdentifierType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="ContentContext" type="{urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1}ContentContextType"/&gt;
 *         &lt;element name="Meta" type="{urn:be:fgov:ejustice:ejustbox:core:v1}MetaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="MessageId" type="{urn:be:fgov:ejustice:ejustbox:core:v1}MessageIdType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsultationMessageType", propOrder = {
    "publicationId",
    "destinationContext",
    "contentContext",
    "meta"
})
public class ConsultationMessageType {

    @XmlElement(name = "PublicationId")
    protected String publicationId;
    @XmlElement(name = "DestinationContext", required = true)
    protected List<EJustboxIdentifierType> destinationContext;
    @XmlElement(name = "ContentContext", required = true)
    protected ContentContextType contentContext;
    @XmlElement(name = "Meta")
    protected List<MetaType> meta;
    @XmlAttribute(name = "MessageId")
    protected String messageId;

    /**
     * Gets the value of the publicationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationId() {
        return publicationId;
    }

    /**
     * Sets the value of the publicationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationId(String value) {
        this.publicationId = value;
    }

    /**
     * Gets the value of the destinationContext property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destinationContext property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestinationContext().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EJustboxIdentifierType }
     * 
     * 
     */
    public List<EJustboxIdentifierType> getDestinationContext() {
        if (destinationContext == null) {
            destinationContext = new ArrayList<EJustboxIdentifierType>();
        }
        return this.destinationContext;
    }

    /**
     * Gets the value of the contentContext property.
     * 
     * @return
     *     possible object is
     *     {@link ContentContextType }
     *     
     */
    public ContentContextType getContentContext() {
        return contentContext;
    }

    /**
     * Sets the value of the contentContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentContextType }
     *     
     */
    public void setContentContext(ContentContextType value) {
        this.contentContext = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaType }
     * 
     * 
     */
    public List<MetaType> getMeta() {
        if (meta == null) {
            meta = new ArrayList<MetaType>();
        }
        return this.meta;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

	@Override
	public String toString() {
		return "ConsultationMessageType [publicationId=" + publicationId + ", destinationContext=" + destinationContext
				+ ", contentContext=" + contentContext + ", meta=" + meta + ", messageId=" + messageId + "]";
	}
    
    

}
