//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.23 at 02:53:20 PM EEST 
//


package org.crama.ejustbox.model.consultation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Recipient of a message
 * 
 * <p>Java class for EJustboxSubstituteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EJustboxSubstituteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:be:fgov:ejustice:ejustbox:core:v1}IdentifierType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Quality" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EJustboxSubstituteType", namespace = "urn:be:fgov:ejustice:ejustbox:core:v1", propOrder = {
    "quality"
})
@XmlSeeAlso({
    SubstituteType.class
})
public class EJustboxSubstituteType
    extends IdentifierType
{
	
	

    public EJustboxSubstituteType() {
		super();
	}

	public EJustboxSubstituteType(String id, String type) {
		super(id, type);
		// TODO Auto-generated constructor stub
	}

	@XmlElement(name = "Quality", required = true)
    protected String quality;

    /**
     * Gets the value of the quality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuality() {
        return quality;
    }

    /**
     * Sets the value of the quality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuality(String value) {
        this.quality = value;
    }

}
