//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.23 at 02:53:20 PM EEST 
//


package org.crama.ejustbox.model.consultation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetBoxInfoRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetBoxInfoRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Actor" type="{urn:be:fgov:ejustice:ejustbox:core:v1}ActorType"/&gt;
 *         &lt;element name="HasNewMessages" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetBoxInfoRequestType", propOrder = {
    "actor",
    "hasNewMessages"
})
public class GetBoxInfoRequestType {

    @XmlElement(name = "Actor", required = true)
    protected ActorType2 actor;
    @XmlElement(name = "HasNewMessages", defaultValue = "false")
    protected Boolean hasNewMessages;

    public GetBoxInfoRequestType(ActorType2 actor, boolean hasNewMessages) {
		this.actor = actor;
		this.hasNewMessages = hasNewMessages;
	}

	/**
     * Gets the value of the actor property.
     * 
     * @return
     *     possible object is
     *     {@link ActorType2 }
     *     
     */
    public ActorType2 getActor() {
        return actor;
    }

    /**
     * Sets the value of the actor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActorType2 }
     *     
     */
    public void setActor(ActorType2 value) {
        this.actor = value;
    }

    /**
     * Gets the value of the hasNewMessages property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasNewMessages() {
        return hasNewMessages;
    }

    /**
     * Sets the value of the hasNewMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasNewMessages(Boolean value) {
        this.hasNewMessages = value;
    }

}
