//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.23 at 02:53:20 PM EEST 
//


package org.crama.ejustbox.model.consultation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.crama.ejustbox.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetBoxInfoRequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetBoxInfoRequest");
    private final static QName _GetMessagesListRequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetMessagesListRequest");
    private final static QName _GetAllejustboxesMessagesListRequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetAllejustboxesMessagesListRequest");
    private final static QName _GetFullMessageRequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetFullMessageRequest");
    private final static QName _MoveMessageRequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "MoveMessageRequest");
    private final static QName _DeleteMessageRequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "DeleteMessageRequest");
    private final static QName _GetHistoryRequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetHistoryRequest");
    private final static QName _GetMessageAcknowledgmentsStatusRequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetMessageAcknowledgmentsStatusRequest");
    private final static QName _InsertOoORequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "InsertOoORequest");
    private final static QName _DeleteOoORequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "DeleteOoORequest");
    private final static QName _GetOoOListRequest_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetOoOListRequest");
    private final static QName _GetBoxInfoResponse_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetBoxInfoResponse");
    private final static QName _GetMessagesListResponse_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetMessagesListResponse");
    private final static QName _GetAllejustboxesMessagesListResponse_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetAllejustboxesMessagesListResponse");
    private final static QName _GetFullMessageResponse_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetFullMessageResponse");
    private final static QName _MoveMessageResponse_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "MoveMessageResponse");
    private final static QName _DeleteMessageResponse_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "DeleteMessageResponse");
    private final static QName _GetHistoryResponse_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetHistoryResponse");
    private final static QName _GetMessageAcknowledgmentsStatusResponse_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetMessageAcknowledgmentsStatusResponse");
    private final static QName _InsertOoOResponse_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "InsertOoOResponse");
    private final static QName _DeleteOoOResponse_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "DeleteOoOResponse");
    private final static QName _GetOoOListResponse_QNAME = new QName("urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", "GetOoOListResponse");
    private final static QName _Author_QNAME = new QName("urn:be:fgov:ejustice:commons:core:v1", "Author");
    private final static QName _Id_QNAME = new QName("urn:be:fgov:ejustice:commons:core:v1", "Id");
    private final static QName _Person_QNAME = new QName("urn:be:fgov:ejustice:commons:core:v1", "Person");
    private final static QName _Status_QNAME = new QName("urn:be:fgov:ejustice:commons:core:v1", "Status");
    private final static QName _StatusCode_QNAME = new QName("urn:be:fgov:ejustice:commons:core:v1", "StatusCode");
    private final static QName _StatusDetail_QNAME = new QName("urn:be:fgov:ejustice:commons:core:v1", "StatusDetail");
    private final static QName _StatusMessage_QNAME = new QName("urn:be:fgov:ejustice:commons:core:v1", "StatusMessage");
    private final static QName _SystemError_QNAME = new QName("urn:be:fgov:ejustice:errors:service:v1", "SystemError");
    private final static QName _BusinessError_QNAME = new QName("urn:be:fgov:ejustice:errors:service:v1", "BusinessError");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.crama.ejustbox.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EJustboxIdentifierType }
     * 
     */
    public EJustboxIdentifierType createEJustboxIdentifierType() {
        return new EJustboxIdentifierType();
    }

    /**
     * Create an instance of {@link GetOoOListResponseType }
     * 
     */
    public GetOoOListResponseType createGetOoOListResponseType() {
        return new GetOoOListResponseType();
    }

    /**
     * Create an instance of {@link GetMessageAcknowledgmentsStatusResponseType }
     * 
     */
    public GetMessageAcknowledgmentsStatusResponseType createGetMessageAcknowledgmentsStatusResponseType() {
        return new GetMessageAcknowledgmentsStatusResponseType();
    }

    /**
     * Create an instance of {@link GetMessageAcknowledgmentsStatusResponseType.AcknowledgmentsStatus }
     * 
     */
    public GetMessageAcknowledgmentsStatusResponseType.AcknowledgmentsStatus createGetMessageAcknowledgmentsStatusResponseTypeAcknowledgmentsStatus() {
        return new GetMessageAcknowledgmentsStatusResponseType.AcknowledgmentsStatus();
    }

    /**
     * Create an instance of {@link GetMessageListResponseType }
     * 
     */
    public GetMessageListResponseType createGetMessageListResponseType() {
        return new GetMessageListResponseType();
    }

    /**
     * Create an instance of {@link GetBoxInfoRequestType }
     * 
     */
    public GetBoxInfoRequestType createGetBoxInfoRequestType(ActorType2 actor, boolean hasNewMails) {
        return new GetBoxInfoRequestType(actor, hasNewMails);
    }

    /**
     * Create an instance of {@link GetMessagesListRequestType }
     * 
     */
    public GetMessagesListRequestType createGetMessagesListRequestType() {
        return new GetMessagesListRequestType();
    }

    /**
     * Create an instance of {@link GetAllejustboxesMessagesListRequestType }
     * 
     */
    public GetAllejustboxesMessagesListRequestType createGetAllejustboxesMessagesListRequestType() {
        return new GetAllejustboxesMessagesListRequestType();
    }

    /**
     * Create an instance of {@link MessageRequestType }
     * 
     */
    public MessageRequestType createMessageRequestType() {
        return new MessageRequestType();
    }

    /**
     * Create an instance of {@link MoveMessageRequestType }
     * 
     */
    public MoveMessageRequestType createMoveMessageRequestType() {
        return new MoveMessageRequestType();
    }

    /**
     * Create an instance of {@link DeleteMessageRequestType }
     * 
     */
    public DeleteMessageRequestType createDeleteMessageRequestType() {
        return new DeleteMessageRequestType();
    }

    /**
     * Create an instance of {@link GetMessageAcknowledgmentsStatusRequestType }
     * 
     */
    public GetMessageAcknowledgmentsStatusRequestType createGetMessageAcknowledgmentsStatusRequestType() {
        return new GetMessageAcknowledgmentsStatusRequestType();
    }

    /**
     * Create an instance of {@link InsertOoORequestType }
     * 
     */
    public InsertOoORequestType createInsertOoORequestType() {
        return new InsertOoORequestType();
    }

    /**
     * Create an instance of {@link DeleteOoORequestType }
     * 
     */
    public DeleteOoORequestType createDeleteOoORequestType() {
        return new DeleteOoORequestType();
    }

    /**
     * Create an instance of {@link GetOoOListRequestType }
     * 
     */
    public GetOoOListRequestType createGetOoOListRequestType() {
        return new GetOoOListRequestType();
    }

    /**
     * Create an instance of {@link GetBoxInfoResponseType }
     * 
     */
    public GetBoxInfoResponseType createGetBoxInfoResponseType() {
        return new GetBoxInfoResponseType();
    }

    /**
     * Create an instance of {@link GetFullMessageResponseType }
     * 
     */
    public GetFullMessageResponseType createGetFullMessageResponseType() {
        return new GetFullMessageResponseType();
    }

    /**
     * Create an instance of {@link MoveMessageResponseType }
     * 
     */
    public MoveMessageResponseType createMoveMessageResponseType() {
        return new MoveMessageResponseType();
    }

    /**
     * Create an instance of {@link DeleteMessageResponseType }
     * 
     */
    public DeleteMessageResponseType createDeleteMessageResponseType() {
        return new DeleteMessageResponseType();
    }

    /**
     * Create an instance of {@link GetHistoryResponseType }
     * 
     */
    public GetHistoryResponseType createGetHistoryResponseType() {
        return new GetHistoryResponseType();
    }

    /**
     * Create an instance of {@link InsertOoOResponseType }
     * 
     */
    public InsertOoOResponseType createInsertOoOResponseType() {
        return new InsertOoOResponseType();
    }

    /**
     * Create an instance of {@link DeleteOoOResponseType }
     * 
     */
    public DeleteOoOResponseType createDeleteOoOResponseType() {
        return new DeleteOoOResponseType();
    }

    /**
     * Create an instance of {@link SubstituteType }
     * 
     */
    public SubstituteType createSubstituteType() {
        return new SubstituteType();
    }

    /**
     * Create an instance of {@link ConsultationContentType }
     * 
     */
    public ConsultationContentType createConsultationContentType() {
        return new ConsultationContentType();
    }

    /**
     * Create an instance of {@link ContentContextType }
     * 
     */
    public ContentContextType createContentContextType() {
        return new ContentContextType();
    }

    /**
     * Create an instance of {@link ConsultationAnnexType }
     * 
     */
    public ConsultationAnnexType createConsultationAnnexType() {
        return new ConsultationAnnexType();
    }

    /**
     * Create an instance of {@link ConsultationDocumentType }
     * 
     */
    public ConsultationDocumentType createConsultationDocumentType() {
        return new ConsultationDocumentType();
    }

    /**
     * Create an instance of {@link ConsultationMessageType }
     * 
     */
    public ConsultationMessageType createConsultationMessageType() {
        return new ConsultationMessageType();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link AuthorRequestType }
     * 
     */
    public AuthorRequestType createAuthorRequestType() {
        return new AuthorRequestType();
    }

    /**
     * Create an instance of {@link PaginationRequestType }
     * 
     */
    public PaginationRequestType createPaginationRequestType() {
        return new PaginationRequestType();
    }

    /**
     * Create an instance of {@link AuthorPaginationRequestType }
     * 
     */
    public AuthorPaginationRequestType createAuthorPaginationRequestType() {
        return new AuthorPaginationRequestType();
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link StatusResponseType }
     * 
     */
    public StatusResponseType createStatusResponseType() {
        return new StatusResponseType();
    }

    /**
     * Create an instance of {@link PaginationResponseType }
     * 
     */
    public PaginationResponseType createPaginationResponseType() {
        return new PaginationResponseType();
    }

    /**
     * Create an instance of {@link PaginationStatusResponseType }
     * 
     */
    public PaginationStatusResponseType createPaginationStatusResponseType() {
        return new PaginationStatusResponseType();
    }

    /**
     * Create an instance of {@link AuthorType }
     * 
     */
    public AuthorType createAuthorType() {
        return new AuthorType();
    }

    /**
     * Create an instance of {@link IdType }
     * 
     */
    public IdType createIdType() {
        return new IdType();
    }

    /**
     * Create an instance of {@link ActorType }
     * 
     */
    public ActorType createActorType() {
        return new ActorType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link StatusCodeType }
     * 
     */
    public StatusCodeType createStatusCodeType() {
        return new StatusCodeType();
    }

    /**
     * Create an instance of {@link StatusDetailType }
     * 
     */
    public StatusDetailType createStatusDetailType() {
        return new StatusDetailType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link AcknowledgmentType }
     * 
     */
    public AcknowledgmentType createAcknowledgmentType() {
        return new AcknowledgmentType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link EJustboxSubstituteType }
     * 
     */
    public EJustboxSubstituteType createEJustboxSubstituteType() {
        return new EJustboxSubstituteType();
    }

    /**
     * Create an instance of {@link MetaType }
     * 
     */
    public MetaType createMetaType() {
        return new MetaType();
    }

    /**
     * Create an instance of {@link CustomMetaType }
     * 
     */
    public CustomMetaType createCustomMetaType() {
        return new CustomMetaType();
    }

    /**
     * Create an instance of {@link ContentInfoType }
     * 
     */
    public ContentInfoType createContentInfoType() {
        return new ContentInfoType();
    }

    /**
     * Create an instance of {@link ContentSpecificationType }
     * 
     */
    public ContentSpecificationType createContentSpecificationType() {
        return new ContentSpecificationType();
    }

    /**
     * Create an instance of {@link MessageInfoType }
     * 
     */
    public MessageInfoType createMessageInfoType() {
        return new MessageInfoType();
    }

    /**
     * Create an instance of {@link ActorType2 }
     * 
     */
    public ActorType2 createActorType2(String id, String type, String quality, String name) {
        return new ActorType2(id, type, quality, name);
    }

    /**
     * Create an instance of {@link SystemErrorType }
     * 
     */
    public SystemErrorType createSystemErrorType() {
        return new SystemErrorType();
    }

    /**
     * Create an instance of {@link BusinessErrorType }
     * 
     */
    public BusinessErrorType createBusinessErrorType() {
        return new BusinessErrorType();
    }

    /**
     * Create an instance of {@link ServiceErrorType }
     * 
     */
    public ServiceErrorType createServiceErrorType() {
        return new ServiceErrorType();
    }

    /**
     * Create an instance of {@link TraceType }
     * 
     */
    public TraceType createTraceType() {
        return new TraceType();
    }

    /**
     * Create an instance of {@link LocalisedStringType }
     * 
     */
    public LocalisedStringType createLocalisedStringType() {
        return new LocalisedStringType();
    }

    /**
     * Create an instance of {@link ErrorType2 }
     * 
     */
    public ErrorType2 createErrorType2() {
        return new ErrorType2();
    }

    /**
     * Create an instance of {@link EJustboxIdentifierType.User }
     * 
     */
    public EJustboxIdentifierType.User createEJustboxIdentifierTypeUser() {
        return new EJustboxIdentifierType.User();
    }

    /**
     * Create an instance of {@link GetOoOListResponseType.OoO }
     * 
     */
    public GetOoOListResponseType.OoO createGetOoOListResponseTypeOoO() {
        return new GetOoOListResponseType.OoO();
    }

    /**
     * Create an instance of {@link GetMessageAcknowledgmentsStatusResponseType.AcknowledgmentsStatus.Row }
     * 
     */
    public GetMessageAcknowledgmentsStatusResponseType.AcknowledgmentsStatus.Row createGetMessageAcknowledgmentsStatusResponseTypeAcknowledgmentsStatusRow() {
        return new GetMessageAcknowledgmentsStatusResponseType.AcknowledgmentsStatus.Row();
    }

    /**
     * Create an instance of {@link GetMessageListResponseType.Message }
     * 
     */
    public GetMessageListResponseType.Message createGetMessageListResponseTypeMessage() {
        return new GetMessageListResponseType.Message();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBoxInfoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetBoxInfoRequest")
    public JAXBElement<GetBoxInfoRequestType> createGetBoxInfoRequest(GetBoxInfoRequestType value) {
        return new JAXBElement<GetBoxInfoRequestType>(_GetBoxInfoRequest_QNAME, GetBoxInfoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessagesListRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetMessagesListRequest")
    public JAXBElement<GetMessagesListRequestType> createGetMessagesListRequest(GetMessagesListRequestType value) {
        return new JAXBElement<GetMessagesListRequestType>(_GetMessagesListRequest_QNAME, GetMessagesListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllejustboxesMessagesListRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetAllejustboxesMessagesListRequest")
    public JAXBElement<GetAllejustboxesMessagesListRequestType> createGetAllejustboxesMessagesListRequest(GetAllejustboxesMessagesListRequestType value) {
        return new JAXBElement<GetAllejustboxesMessagesListRequestType>(_GetAllejustboxesMessagesListRequest_QNAME, GetAllejustboxesMessagesListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetFullMessageRequest")
    public JAXBElement<MessageRequestType> createGetFullMessageRequest(MessageRequestType value) {
        return new JAXBElement<MessageRequestType>(_GetFullMessageRequest_QNAME, MessageRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MoveMessageRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "MoveMessageRequest")
    public JAXBElement<MoveMessageRequestType> createMoveMessageRequest(MoveMessageRequestType value) {
        return new JAXBElement<MoveMessageRequestType>(_MoveMessageRequest_QNAME, MoveMessageRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteMessageRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "DeleteMessageRequest")
    public JAXBElement<DeleteMessageRequestType> createDeleteMessageRequest(DeleteMessageRequestType value) {
        return new JAXBElement<DeleteMessageRequestType>(_DeleteMessageRequest_QNAME, DeleteMessageRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetHistoryRequest")
    public JAXBElement<MessageRequestType> createGetHistoryRequest(MessageRequestType value) {
        return new JAXBElement<MessageRequestType>(_GetHistoryRequest_QNAME, MessageRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessageAcknowledgmentsStatusRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetMessageAcknowledgmentsStatusRequest")
    public JAXBElement<GetMessageAcknowledgmentsStatusRequestType> createGetMessageAcknowledgmentsStatusRequest(GetMessageAcknowledgmentsStatusRequestType value) {
        return new JAXBElement<GetMessageAcknowledgmentsStatusRequestType>(_GetMessageAcknowledgmentsStatusRequest_QNAME, GetMessageAcknowledgmentsStatusRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InsertOoORequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "InsertOoORequest")
    public JAXBElement<InsertOoORequestType> createInsertOoORequest(InsertOoORequestType value) {
        return new JAXBElement<InsertOoORequestType>(_InsertOoORequest_QNAME, InsertOoORequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteOoORequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "DeleteOoORequest")
    public JAXBElement<DeleteOoORequestType> createDeleteOoORequest(DeleteOoORequestType value) {
        return new JAXBElement<DeleteOoORequestType>(_DeleteOoORequest_QNAME, DeleteOoORequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOoOListRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetOoOListRequest")
    public JAXBElement<GetOoOListRequestType> createGetOoOListRequest(GetOoOListRequestType value) {
        return new JAXBElement<GetOoOListRequestType>(_GetOoOListRequest_QNAME, GetOoOListRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBoxInfoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetBoxInfoResponse")
    public JAXBElement<GetBoxInfoResponseType> createGetBoxInfoResponse(GetBoxInfoResponseType value) {
        return new JAXBElement<GetBoxInfoResponseType>(_GetBoxInfoResponse_QNAME, GetBoxInfoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessageListResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetMessagesListResponse")
    public JAXBElement<GetMessageListResponseType> createGetMessagesListResponse(GetMessageListResponseType value) {
        return new JAXBElement<GetMessageListResponseType>(_GetMessagesListResponse_QNAME, GetMessageListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessageListResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetAllejustboxesMessagesListResponse")
    public JAXBElement<GetMessageListResponseType> createGetAllejustboxesMessagesListResponse(GetMessageListResponseType value) {
        return new JAXBElement<GetMessageListResponseType>(_GetAllejustboxesMessagesListResponse_QNAME, GetMessageListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetFullMessageResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetFullMessageResponse")
    public JAXBElement<GetFullMessageResponseType> createGetFullMessageResponse(GetFullMessageResponseType value) {
        return new JAXBElement<GetFullMessageResponseType>(_GetFullMessageResponse_QNAME, GetFullMessageResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MoveMessageResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "MoveMessageResponse")
    public JAXBElement<MoveMessageResponseType> createMoveMessageResponse(MoveMessageResponseType value) {
        return new JAXBElement<MoveMessageResponseType>(_MoveMessageResponse_QNAME, MoveMessageResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteMessageResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "DeleteMessageResponse")
    public JAXBElement<DeleteMessageResponseType> createDeleteMessageResponse(DeleteMessageResponseType value) {
        return new JAXBElement<DeleteMessageResponseType>(_DeleteMessageResponse_QNAME, DeleteMessageResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetHistoryResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetHistoryResponse")
    public JAXBElement<GetHistoryResponseType> createGetHistoryResponse(GetHistoryResponseType value) {
        return new JAXBElement<GetHistoryResponseType>(_GetHistoryResponse_QNAME, GetHistoryResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMessageAcknowledgmentsStatusResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetMessageAcknowledgmentsStatusResponse")
    public JAXBElement<GetMessageAcknowledgmentsStatusResponseType> createGetMessageAcknowledgmentsStatusResponse(GetMessageAcknowledgmentsStatusResponseType value) {
        return new JAXBElement<GetMessageAcknowledgmentsStatusResponseType>(_GetMessageAcknowledgmentsStatusResponse_QNAME, GetMessageAcknowledgmentsStatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InsertOoOResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "InsertOoOResponse")
    public JAXBElement<InsertOoOResponseType> createInsertOoOResponse(InsertOoOResponseType value) {
        return new JAXBElement<InsertOoOResponseType>(_InsertOoOResponse_QNAME, InsertOoOResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteOoOResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "DeleteOoOResponse")
    public JAXBElement<DeleteOoOResponseType> createDeleteOoOResponse(DeleteOoOResponseType value) {
        return new JAXBElement<DeleteOoOResponseType>(_DeleteOoOResponse_QNAME, DeleteOoOResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOoOListResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1", name = "GetOoOListResponse")
    public JAXBElement<GetOoOListResponseType> createGetOoOListResponse(GetOoOListResponseType value) {
        return new JAXBElement<GetOoOListResponseType>(_GetOoOListResponse_QNAME, GetOoOListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:commons:core:v1", name = "Author")
    public JAXBElement<AuthorType> createAuthor(AuthorType value) {
        return new JAXBElement<AuthorType>(_Author_QNAME, AuthorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:commons:core:v1", name = "Id")
    public JAXBElement<IdType> createId(IdType value) {
        return new JAXBElement<IdType>(_Id_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:commons:core:v1", name = "Person")
    public JAXBElement<ActorType> createPerson(ActorType value) {
        return new JAXBElement<ActorType>(_Person_QNAME, ActorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:commons:core:v1", name = "Status")
    public JAXBElement<StatusType> createStatus(StatusType value) {
        return new JAXBElement<StatusType>(_Status_QNAME, StatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:commons:core:v1", name = "StatusCode")
    public JAXBElement<StatusCodeType> createStatusCode(StatusCodeType value) {
        return new JAXBElement<StatusCodeType>(_StatusCode_QNAME, StatusCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusDetailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:commons:core:v1", name = "StatusDetail")
    public JAXBElement<StatusDetailType> createStatusDetail(StatusDetailType value) {
        return new JAXBElement<StatusDetailType>(_StatusDetail_QNAME, StatusDetailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:commons:core:v1", name = "StatusMessage")
    public JAXBElement<String> createStatusMessage(String value) {
        return new JAXBElement<String>(_StatusMessage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemErrorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:errors:service:v1", name = "SystemError")
    public JAXBElement<SystemErrorType> createSystemError(SystemErrorType value) {
        return new JAXBElement<SystemErrorType>(_SystemError_QNAME, SystemErrorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessErrorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:be:fgov:ejustice:errors:service:v1", name = "BusinessError")
    public JAXBElement<BusinessErrorType> createBusinessError(BusinessErrorType value) {
        return new JAXBElement<BusinessErrorType>(_BusinessError_QNAME, BusinessErrorType.class, null, value);
    }

}
