//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.23 at 02:53:20 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:be:fgov:ejustice:ejustbox:consultation:protocol:v1")
package org.crama.ejustbox.model.consultation;
