//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.23 at 02:53:20 PM EEST 
//


package org.crama.ejustbox.model.consultation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for SystemErrors.
 * 
 * <p>Java class for SystemErrorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SystemErrorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:be:fgov:ejustice:errors:service:v1}ServiceErrorType"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemErrorType", namespace = "urn:be:fgov:ejustice:errors:service:v1")
public class SystemErrorType
    extends ServiceErrorType
{

	@Override
	public String toString() {
		return "SystemErrorType [actor=" + actor + ", dateTime=" + dateTime + ", trace=" + trace + ", origin=" + origin
				+ ", code=" + code + ", message=" + message + ", retry=" + retry + ", contact=" + contact + ", id=" + id
				+ "]";
	}

	

}
