//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 06:38:38 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:be:fgov:ejustice:commons:core:v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.fgov.ejustice.commons.core.v1;
